//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryItemId { get; set; }
        public string InventoryDescription { get; set; }
        public decimal InventoryUnitPrice { get; set; }
        public int InventoryQuantities { get; set; }
        public decimal InventoryUnitCost { get; set; }
        public decimal InventoryValue { get; set; }
        public string InventoryNotes { get; set; }
    }
}
